export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_LOADNG = 'LOGIN_LOADNG';
export const LOGIN_ERROR = 'LOGIN_ERROR';


export const REG_SUCESS = 'REG_SUCESS';
export const REG_LOADNG = 'REG_LOADNG';
export const REG_ERROR = 'REG_ERROR';

export const FORGETEMAIL_SUCESS = 'FORGETEMAIL_SUCESS';
export const FORGETEMAIL_LOADNG = 'FORGETEMAIL_LOADNG';
export const FORGETEMAIL_ERROR = 'FORGETEMAIL_ERROR';

export const FORGETOTP_SUCESS = 'FORGETOTP_SUCESS';
export const FORGETPASSWORD_SUCESS = 'FORGETPASSWORD_SUCESS';

export const FECTCH_DASHDATA_SUCCESS = 'FECTCH_DASHDATA_SUCCESS';
export const FECTCH_DASHDATA_LOADING = 'FECTCH_DASHDATA_LOADING';
export const FECTCH_DASHDATA_ERROR = 'FECTCH_DASHDATA_ERROR';

export const FECTCH_INTERESTS_SUCCESS = 'FECTCH_INTERESTS_SUCCESS';
export const FECTCH_INTERESTS_LOADING = 'FECTCH_INTERESTS_LOADING';
export const FECTCH_INTERESTS_ERROR = 'FECTCH_INTERESTS_ERROR';

export const FECTCH_CATEGORY_SUCCESS = 'FECTCH_CATEGORY_SUCCESS';
export const FECTCH_CATEGORY_LOADING = 'FECTCH_CATEGORY_LOADING';
export const FECTCH_CATEGORY_ERROR = 'FECTCH_CATEGORY_ERROR';

export const FECTCH_SUBINTERESTS_SUCCESS = 'FECTCH_SUBINTERESTS_SUCCESS';
export const FECTCH_SUBINTERESTS_LOADING = 'FECTCH_SUBINTERESTS_LOADING';
export const FECTCH_SUBINTERESTS_ERROR = 'FECTCH_SUBINTERESTS_ERROR';

export const FECTCH_ADDINTERESTS_SUCCESS = 'FECTCH_ADDINTERESTS_SUCCESS';
export const FECTCH_ADDINTERESTS_LOADING = 'FECTCH_ADDINTERESTS_LOADING';
export const FECTCH_ADDINTERESTS_ERROR = 'FECTCH_ADDINTERESTS_ERROR';

export const FECTCH_ADDSUBINTERESTS_SUCCESS = 'FECTCH_ADDSUBINTERESTS_SUCCESS';
export const FECTCH_ADDSUBINTERESTS_LOADING = 'FECTCH_ADDSUBINTERESTS_LOADING';
export const FECTCH_ADDSUBINTERESTS_ERROR = 'FECTCH_ADDSUBINTERESTS_ERROR';

export const FECTCH_EDITINTERESTS_SUCCESS = 'FECTCH_EDITINTERESTS_SUCCESS';
export const FECTCH_EDITINTERESTS_LOADING = 'FECTCH_EDITINTERESTS_LOADING';
export const FECTCH_EDITINTERESTS_ERROR = 'FECTCH_EDINTERESTS_ERROR';

export const FECTCH_EDITSUBINTERESTS_SUCCESS = 'FECTCH_EDITSUBINTERESTS_SUCCESS';
export const FECTCH_EDITSUBINTERESTS_LOADING = 'FECTCH_EDITSUBINTERESTS_LOADING';
export const FECTCH_EDITSUBINTERESTS_ERROR = 'FECTCH_EDITSUBINTERESTS_ERROR';

export const FETCH_BLOCK_SUCESS = 'FETCH_BLOCK_SUCESS';
export const FETCH_BLOCK_LOADING = 'FETCH_BLOCK_LOADING';
export const FETCH_BLOCK_ERROR = 'FETCH_BLOCK_ERROR';

export const FETCH_BLOCKSUB_SUCESS = 'FETCH_BLOCKSUB_SUCESS';
export const FETCH_BLOCKSUB_LOADING = 'FETCH_BLOCKSUB_LOADING';
export const FETCH_BLOCKSUB_ERROR = 'FETCH_BLOCKSUB_ERROR';

export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_SUCESS = 'FETCH_USER_SUCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCHDELETE_USER_LOADING = 'FETCHDELETE_USER_LOADING';
export const FETCHDELETE_USER_SUCESS = 'FETCHDELETE_USER_SUCESS';
export const FETCHDELETE_USER_ERROR = 'FETCHDELETE_USER_ERROR';

export const FETCHUSER_BLOCK_SUCESS = 'FETCHUSER_BLOCK_SUCESS';
export const FETCHUSER_BLOCK_LOADING = 'FETCHUSER_BLOCK_LOADING';
export const FETCHUSER_BLOCK_ERROR = 'FETCUSER_BLOCK_ERROR';

export const USER_DATA_LOADING = 'USER_DATA_LOADING';
export const USER_DATA_SUCESS = 'USER_DATA_SUCESS';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';

export const USERBANK_DATA_LOADING = 'USERBANK_DATA_LOADING';
export const USERBANK_DATA_SUCESS = 'USERBANK_DATA_SUCESS';
export const USERBANK_DATA_ERROR = 'USERBANK_DATA_ERROR';

export const USER_GRPLIST_LOADING = 'USER_GRPLIST_LOADING';
export const USER_GRPLIST_SUCCESS = 'USER_GRPLIST_SUCCESS';
export const USER_GRPLIST_ERROR = 'USER_GRPLIST_ERROR';

export const ADMIN_CONNECTION_LIST_LOADING = 'ADMIN_CONNECTION_LIST_LOADING';
export const ADMIN_CONNECTION_LIST_SUCCESS = 'ADMIN_CONNECTION_LIST_SUCCESS';
export const ADMIN_CONNECTION_LIST_ERROR = 'ADMIN_CONNECTION_LIST_ERROR';
export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const FETCH_DATA_LOADING = 'FETCH_DATA_LOADING,';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const ADD_CLUE_LOADING = 'ADD_CLUE_LOADING';
export const ADD_CLUE_SUCCESS = 'ADD_CLUE_SUCCESS';
export const ADD_CLUE_ERROR = 'ADD_CLUE_ERROR';

export const DELETE_CLUE_LOADING = 'DELETE_CLUE_LOADING';
export const DELETE_CLUE_SUCCESS = 'DELETE_CLUE_SUCCESS';
export const DELETE_CLUE_ERROR = 'DELETE_CLUE_ERROR';

export const EDIT_CLUE_LOADING = 'EDIT_CLUE_LOADING';
export const EDIT_CLUE_SUCCESS = 'EDIT_CLUE_SUCCESS';
export const EDIT_CLUE_ERROR = 'EDIT_CLUE_ERROR';

export const GAME_LOADING = 'GAME_LOADING';
export const GAME_SUCCESS = 'GAME_SUCCESS';
export const GAME_ERROR = 'GAME_ERROR';

export const GAMELIST_LOADING = 'GAMELIST_LOADING';
export const GAMELIST_SUCCESSPRIVATE = 'GAMELIST_SUCCESSPRIVATE';
export const GAMELIST_SUCCESSPUBLIC = 'GAMELIST_SUCCESSPUBLIC';
export const GAMELIST_ERROR = 'GAMELIST_ERROR';

export const GAMELISTDELETE_LOADING = 'GAMELISTDELETE_LOADING';
export const GAMELISTDELETE_SUCCESS = 'GAMELISTDELETE_SUCCESS';
export const GAMELISTDELETE_ERROR = 'GAMELISTDELETE_ERROR';

export const BOOKINGDATA_LOADING = 'BOOKINGDATA_LOADING';
export const BOOKINGDATA_SUCCESS = 'BOOKINGDATA_SUCCESS';
export const BOOKINGDATA_ERROR = 'BOOKINGDATA_ERROR';

export const BOOKINGEDIT_LOADING = 'BOOKINGEDIT_LOADING';
export const BOOKINGEDIT_SUCCESS = 'BOOKINGEDIT_SUCCESS';
export const BOOKINGEDIT_ERROR = 'BOOKINGEDIT_ERROR';
export const CHATDELETE_LOADING = 'CHATDELETE_LOADING';
export const CHATDELETE_SUCCESS = 'CHATDELETE_SUCCESS';
export const CHATDELETE_ERROR = 'CHATDELETE_ERROR';

export const CHATADD_LOADING = 'CHATADD_LOADING';
export const CHATADD_SUCCESS = 'CHATADD_SUCCESS';
export const CHATADD_ERROR = 'CHATADD_ERROR';

export const TRASCATION_LOADING = 'TRASCATION_LOADING';
export const TRASCATION_SUCCESS = 'TRASCATION_SUCCESS';
export const TRASCATIONERROR = 'TRASCATION_ERROR';

export const BOOKINGEDIT_LOADING2 = 'BOOKINGEDIT_LOADING2';
export const BOOKINGEDIT_SUCCESS2 = 'BOOKINGEDIT_SUCCESS2';
export const BOOKINGEDIT_ERROR2 = 'BOOKINGEDIT_ERROR2';